[project]
name = "rohan"
version = "0.1.0"
description = "Risk Optimization with Heuristic Agent Network"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.22.1",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
